
services:
  postgres:
    image: 'postgres:14.3-alpine'
    container_name: 'twitter-postgres'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${TWITTER_DB_USERNAME}
      - POSTGRES_PASSWORD=${TWITTER_DB_PASSWORD}
      - POSTGRES_DB=${TWITTER_DB_NAME}


  sonar:
    image: sonarqube:10.2.1-community
    ports:
      - '9000:9000'

